//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AlbatrosSoft.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class Department
    {
        public Department()
        {
            this.Employee = new HashSet<Employee>();
        }
    
        public int DepartmentId { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Employee> Employee { get; set; }
    }
}
